spring:
  application:
    name: event_producer
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080


# docker exec kafka kafka-topics --create --topic event --partitions 1 --replication-factor 1  --if-not-exists --zookeeper zookeeper:2181

# docker-compose exec kafka kafka-topics --describe --topic event --zookeeper zookeeper:2181


# docker-compose exec kafka  bash -c "seq 100 | kafka-console-producer --request-required-acks 1 --broker-list localhost:29092 --topic meu-topico-legal && echo 'Produced 100 messages.'"